### ISSUE TITLE
npm start error - ubuntu 14.04 32 bit

### ISSUE THREAD

**Issue by ajayphp** [rodrigopolo/node-mongo-demo#1]
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/home/me/.nvm/versions/node/v4.4.4/bin/node" "/home/me/.nvm/versions/node/v4.4.4/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! node-mongo-demo@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-mongo-demo@0.0.0 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-mongo-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-mongo-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-mongo-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by rodrigopolo** [comment]
I have tested and reviewed the instructions for the latest version of Ubuntu x64, Ubuntu x32 isn't very well supported for MongoDB.
https://github.com/rodrigopolo/node-mongo-demo/tree/master/install_instructions
